# Generated by Django 5.2.6 on 2025-12-29 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_batch_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=100)),
                ('filename', models.CharField(max_length=500)),
                ('file_key', models.CharField(max_length=500)),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
                ('imported_by_email', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'po_import_logs',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_payto_id', models.CharField(db_index=True, max_length=50)),
                ('po_payto_name', models.CharField(db_index=True, max_length=255)),
                ('po_company', models.CharField(db_index=True, max_length=50)),
                ('po_branch', models.CharField(db_index=True, max_length=50)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order_date', models.DateField(db_index=True)),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('import_batch_id', models.CharField(db_index=True, default='legacy', max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by_email', models.CharField(max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['company_code', 'po_payto_name', '-order_date'], name='purchase_or_company_15f345_idx'), models.Index(fields=['company_code', 'po_branch', '-order_date'], name='purchase_or_company_32a245_idx'), models.Index(fields=['company_code', 'po_company', '-order_date'], name='purchase_or_company_384797_idx'), models.Index(fields=['company_code', '-order_date'], name='purchase_or_company_26c741_idx')],
            },
        ),
    ]
