# Generated by Django 5.2.6 on 2025-12-18 02:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='import_batch_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='import_batch_id',
            field=models.CharField(db_index=True, default='legacy', max_length=100),
        ),
    ]
