# Generated by Django 5.2.6 on 2025-12-12 16:55

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_key', models.CharField(max_length=500, unique=True)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('uploaded_by_user_id', models.CharField(max_length=100)),
                ('uploaded_by_email', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'company_files',
                'indexes': [models.Index(fields=['company_code', '-uploaded_at'], name='company_fil_company_9650fe_idx'), models.Index(fields=['company_code', 'is_deleted'], name='company_fil_company_4b752d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('file_id', models.CharField(max_length=100)),
                ('file_key', models.CharField(max_length=500)),
                ('operation', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=255)),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'file_access_logs',
                'indexes': [models.Index(fields=['company_code', '-timestamp'], name='file_access_company_905024_idx'), models.Index(fields=['file_id', '-timestamp'], name='file_access_file_id_489e85_idx'), models.Index(fields=['operation', '-timestamp'], name='file_access_operati_cf598c_idx')],
            },
        ),
    ]
