# Generated by Django 5.2.6 on 2025-12-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfile',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='fileaccesslog',
            name='_id',
        ),
        migrations.AddField(
            model_name='companyfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='fileaccesslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
