# Generated by Django - Initial migration for vendors app
# This app has no models (uses ERP API only), so this is an empty migration

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
